
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2'
version_full = 'bb79c623b048fbb05b6dbe46c02351672e345883'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

