
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.1'
version_full = '372b7a8411224a06cda187b1b2e294ca20d6489a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

