
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.5'
version_full = 'b23db0def7578ea47006820bd9c9d5a49ee91ee0'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
