
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.2'
version_full = '2e675b1ed8df6eac95c6bc80388a2e39fb750927'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

