
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.3'
version_full = '7d141dfa345e160eaa85db6617bcf6f01ae002ec'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

