
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.0'
version_full = '6916ac9471d8a4fd6792e13badacb9c43c850a24'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

