
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.3'
version_full = 'deab221ad296aa9926d7dc8a07d4e2323d05a5ca'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

