__version__ = "0.1.30"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.1.30)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '65b8ad4f1f7328f3c30224302dc5a4e2991a3f5c'
__git_head_subject__ = 'Finished release v0.1.30.'
__git_head_message__ = ''
__git_dirty_diff__ = ''