
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.0'
version_full = 'd8e7930a66eb311891d3873760ce23e9ca136c41'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

