
# This file is automatically generated by setup.py
short_version = '0.3.0'
version = '0.3.0'
full_version = '0.3.0.dev-fa1993b'
git_revision = 'fa1993b6deccb6fd7d66d7859668db1757fd95ae'
release = False

if not release:
    version = full_version
