
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.5'
version_full = '1fccfb0dd2d7b8e7691d662199dd692934260f90'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

