
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = 'b3db1c75b7b23c8cd52544f36c23425ea99e078d'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
