# This file was auto-generated by salt's setup on Wednesday, 06 May 2015 @ 18:05:35 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 0, 0, 0, 0, None)
