
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.13'
version_full = '8600f86f571ca5e8937305f996b384060b83b49a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

