
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.15'
version_full = '59695c89ae9c9bd4227f0d6463eef21cb952f82c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

