
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.2b3'
version_full = '31764c22036c464b7ae3263b2bc35e17e06bdefd'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
