
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.2'
version_full = '9a91a442dc69a28aa21b2041579aaeeb210a8595'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

