"""empty message

Revision ID: 2615e2b854
Revises: None
Create Date: 2015-05-22 00:10:14.590147

"""

# revision identifiers, used by Alembic.
revision = '2615e2b854'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
