__version__ = "0.2.2"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.2.2)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '5b2ed04c30d530a81b786afd894addb5fcac5e6e'
__git_head_subject__ = 'HPT-1531 handling more port speeds'
__git_head_message__ = ''
__git_dirty_diff__ = ''