
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.3'
version_full = 'b7c81e01e174d1279ed5213b0e9cdfc961f0aded'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

