language: python
python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "nightly"
install: pip install .
script: py.test
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
notifications:
    email: false
matrix:
    fast_finish: true
