
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.3'
version_full = '42ce88b02c0cdc8bd4397c65d9acdc3175acf98c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

