# Autogenerated by Astropy's setup.py on 2015-05-29 15:44:39.095660
from __future__ import unicode_literals
import datetime

version = "0.4.6"
githash = "3be01b5f61e6c1a1913b699a1cfdc5d998050eb1"


major = 0
minor = 4
bugfix = 6

release = True
timestamp = datetime.datetime(2015, 5, 29, 15, 44, 39, 95660)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
