
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.8'
version_full = '62f351411c8d6371e54c3e66c358c90c87f1c94e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

