# -*- coding: utf-8 -*-
#
# This file is part of Flask-IIIF
# Copyright (C) 2014 CERN.
#
# Flask-IIIF is free software; you can redistribute it and/or modify
# it under the terms of the Revised BSD License; see LICENSE file for
# more details.

# Travis CI file, that integrates with coveralls for reporting test coverage.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install coveralls pep257"
  - "travis_retry pip install pytest pytest-pep8 pytest-cov pytest-cache"
  - "travis_retry pip install -e .[docs]"

script:
  - pep257 flask_iiif
  - "sphinx-build -qnNW docs docs/_build/html"
  - python setup.py test

after_success:
  - coveralls

notifications:
  email: false
