# Define holodeck metrics
METRIC_QUESTIONNAIRE_COMPLETED = 1
METRIC_QUESTIONNAIRE_INCOMPLETE = 2
METRIC_QUESTIONNAIRE_PENDING = 3
METRIC_QUESTIONNAIRE_REJECTED = 4

QUESTIONNAIRE_METRICS = (
    (METRIC_QUESTIONNAIRE_COMPLETED, 'Completed Questionnaires'),
    (METRIC_QUESTIONNAIRE_INCOMPLETE, 'Incomplete Questionnaires'),
    (METRIC_QUESTIONNAIRE_PENDING, 'Pending Questionnaires'),
    (METRIC_QUESTIONNAIRE_REJECTED, 'Rejected Questionnaires'),
)


# Define questionnaire participation status
QUESTIONNAIRE_COMPLETED = 1
QUESTIONNAIRE_INCOMPLETE = 2
QUESTIONNAIRE_PENDING = 3
QUESTIONNAIRE_REJECTED = 4
