
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.4'
version_full = 'a57965bb9c63a2b8c5dedd27032a47a107dd8e71'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

