
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.14'
version_full = 'a7ea94c79df7d0228adbed8e4163a59d17642629'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

