language: python
python: '2.7'
sudo: false
cache:
  directories:
  - eggs
install:
- python bootstrap.py -v 1.7.1 -c test-$PLONE_VERSION.cfg
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg annotate
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg
script:
- bin/test
env:
  matrix:
    - PLONE_VERSION=4.x
    - PLONE_VERSION=5.x
