language: python
python:
  - 2.7
env:
  - TOX_ENV=py27_dj17
  - TOX_ENV=py32_dj17
  - TOX_ENV=py33_dj17
  - TOX_ENV=py34_dj17
  - TOX_ENV=py27_dj18
  - TOX_ENV=py32_dj18
  - TOX_ENV=py33_dj18
  - TOX_ENV=py34_dj18
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
