
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.2b5'
version_full = 'b8279ea36d20d312294678d76cbbb066a9ec819b'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
