buildscript: {{cookiecutter.app_name}}/sideloader/build.sh
postinstall: {{cookiecutter.app_name}}/sideloader/postinstall.sh
pip:
 - gunicorn
dependencies:
 - nginx
 - postgresql-server-dev-all
 - libpq-dev
 - postgresql
 - redis-server
