
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5'
version_full = '2cde96e1822de0c26d7b27871f7cf8e05886e13e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

