
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.10'
version_full = '5d88814b29b2e99c140a531bef194f475d78b03a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

