
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2'
version_full = '6ff37a3dc2c028d8784919009f3099b1e3349c81'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

