
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.0.6'
version_full = '7373bdaf7440a4daa320095478342eed1d57235e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

