# Docker Infrastructure (see http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ )
sudo: false

language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install --use-mirrors -r test-requirements.txt
  - pip install --use-mirrors coveralls
script:
  - flake8 py2pack
  - coverage run --source=py2pack setup.py test
after_success:
  coveralls
