"""Constants for FDFS.
"""

QUERY_WITHOUT_GROUP = 101
FDFS_FILE_EXT_NAME_MAX_LEN = 6
FDFS_GROUP_NAME_MAX_LEN = 16
IP_ADDRESS_SIZE = 16
FDFS_PROTO_PKG_LEN_SIZE = 8
STORAGE_PROTO_CMD_DOWNLOAD_FILE = 14
STORAGE_PROTO_CMD_UPLOAD_FILE = 11
TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITH_GROUP_ONE = 104
