
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class PaymentSettings(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getThirdPartyPaymentWorkflows(self,):
		""" Retrieves the details of the third-party payment service workflows configured for the site.
		
		Returns:
			| array of ExternalPaymentWorkflowDefinition 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/settings/checkout/paymentsettings/thirdpartyworkflows", "GET", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	