os:
  - linux
  - osx
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install django
  - pip install sphinx
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - python setup.py test
  - python setup.py install
  - ./tests/system_test.sh
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3b31825a7e1c501c9c1f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
