language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
  matrix:
  - PLONE_VERSION=4
  - PLONE_VERSION=5
matrix:
  fast_finish: true
install:
- sed -ie "s#test-4.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
script:
- bin/test
- bin/code-analysis
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
