
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.4-dirty'
version_full = 'c93ffaf99781c081f609213e45b898f400dc4cc5-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

