
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.2b1'
version_full = '6f6308c54249c236d0fa70350a5f00451fd06456'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
