
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.5'
version_full = 'b808366aa4eff59e9e22a9bc4a8c1b0a1c808a76'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

