
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.7'
version_full = '8bc1b4c85966221c2d11afea8b1c3cbc0cae3540'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

