language: python
python:
  - "2.7"
  - "3.4"
before_install: pip install pytest-cov
install: pip install -r requirements.txt
script: py.test --cov-report term-missing --cov APPLICATION_NAME test
notifications:
  email:
    on_success: always
    on_failure: always
