
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.3'
version_full = '8e3e1e62ee4e68303a91bb952c11bb44f26b2487'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

