
# /Users/haoxun/Data/Project/sdataflow/sdataflow/lang/generated_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x0e\xed\xc7\xc7&\xae}\xe8T/E\xdf\xd9f\xabO'
    
_lr_action_items = {'DOUBLE_HYPHENS':([4,],[11,]),'ID':([0,1,2,3,6,7,8,10,12,13,14,15,16,18,19,20,],[4,9,-4,-2,-5,-3,4,-7,18,19,-1,-9,-10,-6,-11,-8,]),'$end':([2,3,6,7,8,14,15,16,18,19,],[-4,-2,-5,-3,0,-1,-9,-10,-6,-11,]),'BRACKET_RIGHT':([9,],[15,]),'ARROW':([4,5,15,17,],[10,13,-9,20,]),'BRACKET_LEFT':([0,2,3,6,7,8,10,11,14,15,16,18,19,],[1,-4,-2,-5,-3,1,1,1,-1,-9,-10,-6,-11,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'entity_to_outcome':([0,8,],[2,2,]),'single_stat':([0,8,],[3,14,]),'outcome':([0,8,10,11,],[5,5,16,17,]),'outcome_to_entity':([0,8,],[6,6,]),'entity_to_entity':([0,8,],[7,7,]),'general_arrow':([4,],[12,]),'stats':([0,],[8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stats","S'",1,None,None,None),
  ('stats -> stats single_stat','stats',2,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',33),
  ('stats -> single_stat','stats',1,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',34),
  ('single_stat -> entity_to_entity','single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',44),
  ('single_stat -> entity_to_outcome','single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',45),
  ('single_stat -> outcome_to_entity','single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',46),
  ('entity_to_entity -> ID general_arrow ID','entity_to_entity',3,'p_entity_to_entity','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',51),
  ('general_arrow -> ARROW','general_arrow',1,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',64),
  ('general_arrow -> DOUBLE_HYPHENS outcome ARROW','general_arrow',3,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',65),
  ('outcome -> BRACKET_LEFT ID BRACKET_RIGHT','outcome',3,'p_outcome','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',73),
  ('entity_to_outcome -> ID ARROW outcome','entity_to_outcome',3,'p_entity_to_outcome','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',78),
  ('outcome_to_entity -> outcome ARROW ID','outcome_to_entity',3,'p_outcome_to_entity','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',83),
]
