
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.3'
version_full = 'd94de20769f35c3ae9f773d6bc10dad9b8c00bba'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

