
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.23.16'
version_full = '9423b56a9b37e72ddb199e6b5a2b76b91195d2a7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

