
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2'
version_full = '01c068848807c05aa05de5c292a18bd2fa0940b1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

