
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.8'
version_full = '48ccb0478e8a6152edeaacbe222fe073fdd18029'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

