
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.2'
version_full = '1c04f8ab8ec1094620ab474d94f00198de778adc'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
