
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.1'
version_full = '37cdeda0cb6fbe2aa89f25449db1579bb853cce4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

