language: python
python:
  - 3.3
  - 3.4
install:
  - pip install --upgrade setuptools
  - pip install flake8
  - pip install docutils
  - pip install coverage
  - pip install pygments
  - pip install git+https://github.com/KeepSafe/aiohttp.git
  - python setup.py develop

script:
  - flake8 aiohttp examples tests
  - coverage run --source=sockjs setup.py test
  - python setup.py check -rm

script: python setup.py test
