
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1'
version_full = '8a93fc99d23f65d700266015abb6efdda4c5aef6'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
