
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.9'
version_full = '2aac59f1a4fdde0e01b3166734d8f72ee32fe0f1'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

