
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.2'
version_full = '1e895a0c9a76104d241e226faa19ffd70569dc4e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

