
# This file was generated by 'versioneer.py' (1.1) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.3'
version_full = '2436ef7ed478b8ea5baf6339901e9b713f6b664b'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

