
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.21.1'
version_full = '2873336de68be233856a929528d49b5a2f506334'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

