
# /Users/haoxun/Data/Project/sdataflow/sdataflow/lang/generated_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0e\xed\xc7\xc7&\xae}\xe8T/E\xdf\xd9f\xabO'
    
_lr_action_items = {u'DOUBLE_HYPHENS':([7,],[12,]),u'ARROW':([1,7,16,17,],[9,13,-9,20,]),u'BRACKET_LEFT':([0,2,3,5,6,8,10,12,13,15,16,18,19,],[4,4,-3,-2,-5,-4,-1,4,4,-11,-9,-10,-6,]),u'BRACKET_RIGHT':([11,],[16,]),u'ID':([0,2,3,4,5,6,8,9,10,13,14,15,16,18,19,20,],[7,7,-3,11,-2,-5,-4,15,-1,-7,19,-11,-9,-10,-6,-8,]),'$end':([2,3,5,6,8,10,15,16,18,19,],[0,-3,-2,-5,-4,-1,-11,-9,-10,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {u'stats':([0,],[2,]),u'general_arrow':([7,],[14,]),u'entity_to_entity':([0,2,],[3,3,]),u'single_stat':([0,2,],[5,10,]),u'outcome_to_entity':([0,2,],[6,6,]),u'outcome':([0,2,12,13,],[1,1,17,18,]),u'entity_to_outcome':([0,2,],[8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stats","S'",1,None,None,None),
  (u'stats -> stats single_stat',u'stats',2,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',33),
  (u'stats -> single_stat',u'stats',1,'p_stats','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',34),
  (u'single_stat -> entity_to_entity',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',44),
  (u'single_stat -> entity_to_outcome',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',45),
  (u'single_stat -> outcome_to_entity',u'single_stat',1,'p_single_stat','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',46),
  (u'entity_to_entity -> ID general_arrow ID',u'entity_to_entity',3,'p_entity_to_entity','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',51),
  (u'general_arrow -> ARROW',u'general_arrow',1,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',64),
  (u'general_arrow -> DOUBLE_HYPHENS outcome ARROW',u'general_arrow',3,'p_general_arrow','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',65),
  (u'outcome -> BRACKET_LEFT ID BRACKET_RIGHT',u'outcome',3,'p_outcome','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',73),
  (u'entity_to_outcome -> ID ARROW outcome',u'entity_to_outcome',3,'p_entity_to_outcome','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',78),
  (u'outcome_to_entity -> outcome ARROW ID',u'outcome_to_entity',3,'p_outcome_to_entity','/Users/haoxun/Data/Project/sdataflow/sdataflow/lang/parser.py',83),
]
