# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fillbass.ui'
#
# Created: Thu Apr  9 20:14:49 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 777)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 531))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pitcherEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.pitcherEdit.setObjectName("pitcherEdit")
        self.verticalLayout.addWidget(self.pitcherEdit)
        self.pitcherListWidget = QtGui.QListWidget(self.formLayoutWidget)
        self.pitcherListWidget.setObjectName("pitcherListWidget")
        self.verticalLayout.addWidget(self.pitcherListWidget)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.verticalLayout)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.typeListWidget = QtGui.QListWidget(self.formLayoutWidget)
        self.typeListWidget.setObjectName("typeListWidget")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.typeListWidget)
        self.outputWidget = QtGui.QWidget(self.formLayoutWidget)
        self.outputWidget.setObjectName("outputWidget")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.outputWidget)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.startDateEdit = QtGui.QDateEdit(self.formLayoutWidget)
        self.startDateEdit.setDate(QtCore.QDate(2008, 1, 1))
        self.startDateEdit.setObjectName("startDateEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.startDateEdit)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.endDateEdit = QtGui.QDateEdit(self.formLayoutWidget)
        self.endDateEdit.setDate(QtCore.QDate(2009, 1, 1))
        self.endDateEdit.setObjectName("endDateEdit")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.endDateEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.formLayout_2.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem)
        self.pushButton = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButton)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.formLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFetch_XML_Files = QtGui.QAction(MainWindow)
        self.actionFetch_XML_Files.setObjectName("actionFetch_XML_Files")
        self.actionSet_DB_Path = QtGui.QAction(MainWindow)
        self.actionSet_DB_Path.setObjectName("actionSet_DB_Path")
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionScan_XML_Files = QtGui.QAction(MainWindow)
        self.actionScan_XML_Files.setObjectName("actionScan_XML_Files")
        self.actionUse_DB_Path = QtGui.QAction(MainWindow)
        self.actionUse_DB_Path.setObjectName("actionUse_DB_Path")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuFile.addAction(self.actionScan_XML_Files)
        self.menuFile.addAction(self.actionUse_DB_Path)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "FillBass", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Pitcher", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pitch Types", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Date Begin", None, QtGui.QApplication.UnicodeUTF8))
        self.startDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Date End", None, QtGui.QApplication.UnicodeUTF8))
        self.endDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Save To …", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFetch_XML_Files.setText(QtGui.QApplication.translate("MainWindow", "Fetch XML Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_DB_Path.setText(QtGui.QApplication.translate("MainWindow", "Set DB Path", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Qt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionScan_XML_Files.setText(QtGui.QApplication.translate("MainWindow", "Scan XML Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUse_DB_Path.setText(QtGui.QApplication.translate("MainWindow", "Use DB Path", None, QtGui.QApplication.UnicodeUTF8))

