# Autogenerated by Astropy's setup.py on 2015-04-16 12:07:06.013861
from __future__ import unicode_literals
import datetime

version = "1.0.2"
githash = "c36b85aedcf1f3375c6a6a32daf912a0196d8b4a"


major = 1
minor = 0
bugfix = 2

release = True
timestamp = datetime.datetime(2015, 4, 16, 12, 7, 6, 13861)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
