
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.5'
version_full = 'c235be6a685f83e97d00c1a43f60e89ca3e37709'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

