
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.2-dirty'
version_full = 'e6a6aca3cfef8723c5fd50fb3d20638439f93763-dirty'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

