
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.3'
version_full = 'de68980883fc29b28d403b13adb6d5593d0d54b6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

