
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.3'
version_full = '0e598cb17dd58807c2f701684ad7f3a63e1a68a7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

