
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5'
version_full = '27d9ebe74037f0d31acc6c8cb81fe0d464f37346'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

