
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.1'
version_full = '2b440271e5ea09af66a252314eae35f1353179c7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

