
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.0'
version_full = '5fe2297bfd942ff400772d478ae3c62f8c56584a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

