
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.0.6'
version_full = '3b46c33d44b4b3516a0d76bc004c4081f4b31b0a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

