---
version: 1

# Loggers defined before this configuration are not disabled.
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    # The filename specifies the log file, which defaults to /dev/null,
    # i.e. no file logging. The log file can be reset with the
    # logging.configure filename option.
    filename: /dev/null
    maxBytes: 10485760  # 10MB
    backupCount: 4
    encoding: utf8

loggers:
  application:  # Renamed by the logging.configure function
    level: INFO
    handlers: [file]

root:
  level: INFO
  handlers: [console]
