COLOUR_DICT = {'InvC': "#74bc78",
        'SpaO': "#ec9b6a",   
        'SpaP': "#ec9b6a",
        'SpaQ': "#ec9b6a",
        'SpaR': "#ec9b6a",
        'SpaS': "#ec9b6a",
        'InvA': "#00adef",  
        'PscP': "#f8ed31",
        'OrgB': "#ec9b6a",
        'OrgA': "#ec9b6a",
        'PrgJ': "#8cc63e",
        'PrgK': "#f05a28",
        'PrgH': "#2a388f",
        'InvG': "#9aafcc",
        'InvH': '#9e1e62',
        'InvE': "#00adef",
        'PrgI': "#d91b5b",
        'InvJ': "#00adef",
        'SipC': '#652c90',
        'SipB': '#652c90',
        'SipD': '#652c90',}

HEATMAP_COLUMNS = ['InvC',
        'SpaO',
        'SpaP',
        'SpaQ',
        'SpaR',
        'SpaS',
        'InvA',
        'PscP',
        'OrgB',
        'OrgA',
        'PrgJ',
        'PrgK',
        'PrgH',
        'InvG',
        'InvH',
        'InvE',
        'PrgI',
        'InvJ',
        'SipC',
        'SipB',
        'SipD']

HEATMAP_ABBREVIATIONS = ['C', 'O', 'P', 'Q', 'R', 'S', 'A', 'P', 'B', 'A',
'J', 'K', 'H', 'G', 'H', 'E', 'I', 'J', 'C', 'B', 'D']