complete --command slpkg --long-option help --short-option h --description 'show this help message and exit'
complete --command slpkg --long-option version --short-option v --description 'print version and exit'
complete --command slpkg --short-option a --description 'auto build SBo packages'
complete --command slpkg --short-option b --description 'add, remove packages in blacklist'
complete --command slpkg --short-option q --description 'add, remove SBo packages in queue'
complete --command slpkg --short-option g --description 'configuration file management'
complete --command slpkg --short-option l --description 'list of repositories packages'
complete --command slpkg --short-option c --description 'check for updated packages'
complete --command slpkg --short-option s --description 'download, build & install packages'
complete --command slpkg --short-option t --description 'package tracking dependencies'
complete --command slpkg --short-option p --description 'print package description'
complete --command slpkg --short-option n --description 'view SBo packages through network'
complete --command slpkg --short-option f --description 'find installed packages'
complete --command slpkg --short-option i --description 'install binary packages'
complete --command slpkg --short-option u --description 'upgrade binary packages'
complete --command slpkg --short-option o --description 'reinstall binary packages'
complete --command slpkg --short-option r --description 'remove binary packages'
complete --command slpkg --short-option d --description 'display the contents'
complete --command slpkg --short-option c --long-option upgrade --description 'additional options for upgrade packages'
complete --command slpkg --short-option l --long-option installed --description 'additional options for list installed packages'
complete --command slpkg --short-option l --long-option index --description 'additional options for list indexing packages'
complete --command slpkg --short-option p --long-option color --description 'additional options for print package description with colors'
complete --command slpkg --long-option add --description 'additional options for blacklist and queue'
complete --command slpkg --long-option remove --description 'additional options for blacklist and queue'
complete --command slpkg -a list --description 'option for print list to blacklist and queue'
complete --command slpkg -a build --description 'build packages from queue'
complete --command slpkg -a install --description 'install packages from queue'
complete --command slpkg -a build-install --description 'build and install packages from queue'
complete --command slpkg -a config --description 'configuration file management'
complete --command slpkg -a update --description 'update all package lists'
complete --command slpkg -a upgrade --description 'upgrade all package lists'
complete --command slpkg -a repo-add --description 'add custom repository'
complete --command slpkg -a repo-remove --description 'remove custom repository'
complete --command slpkg -a repo-list --description 'list all repositories'
complete --command slpkg -a repo-info --description 'repository information'
