
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\\a\xf0\xf7\x06{\xd8\xe34\x92~\xcd\x9cM\x10\x12'
    
_lr_action_items = {'{':([0,2,3,8,10,21,22,23,],[1,1,-3,-2,1,-7,-9,-8,]),'$end':([2,3,4,8,21,22,23,],[-1,-3,0,-2,-7,-9,-8,]),'FIELD_SEPARATOR':([5,7,9,10,12,13,19,25,26,32,],[-5,-4,-6,11,11,-12,-13,-14,-15,-20,]),'}':([2,3,5,7,8,9,14,15,16,17,20,21,22,23,],[-1,-3,-5,-4,-2,-6,21,22,-10,23,-11,-7,-9,-8,]),'ALPHANUMERIC':([1,5,6,7,9,10,11,14,18,24,26,27,28,29,30,31,32,],[5,-5,5,-4,5,5,5,5,5,5,5,5,-18,-17,-16,-19,5,]),'NEWLINE':([5,7,9,25,26,32,],[-5,-4,-6,29,-15,-20,]),'NUMERIC':([1,5,6,7,9,10,11,14,18,24,26,27,28,29,30,31,32,],[7,-5,7,-4,7,7,7,7,7,7,7,7,-18,-17,-16,-19,7,]),'/':([5,7,9,25,26,32,],[-5,-4,-6,28,-15,-20,]),',':([5,7,9,25,26,32,],[-5,-4,-6,31,-15,-20,]),'TERMINAL_FIELD':([5,7,9,10,12,13,19,25,26,32,],[-5,-4,-6,16,20,-12,-13,-14,-15,-20,]),'COLON':([5,6,7,9,18,25,26,32,],[-5,10,-4,-6,24,30,-15,-20,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'fields':([10,],[17,]),'subfield_separator':([25,],[27,]),'value_fields':([10,],[12,]),'blocks':([0,10,],[2,2,]),'field_data':([24,],[25,]),'value_field':([10,12,],[13,19,]),'data_chunk':([1,6,9,10,11,14,18,24,26,27,32,],[6,9,9,14,18,9,9,26,9,32,9,]),'header_block':([0,2,10,],[3,8,3,]),'swift_message':([0,10,],[4,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> swift_message","S'",1,None,None,None),
  ('swift_message -> blocks','swift_message',1,'p_swift_message','/home/sal/workspace/mt940/src/mt940/parser.py',68),
  ('blocks -> blocks header_block','blocks',2,'p_blocks0','/home/sal/workspace/mt940/src/mt940/parser.py',75),
  ('blocks -> header_block','blocks',1,'p_blocks1','/home/sal/workspace/mt940/src/mt940/parser.py',82),
  ('data_chunk -> NUMERIC','data_chunk',1,'p_data_chunk0','/home/sal/workspace/mt940/src/mt940/parser.py',89),
  ('data_chunk -> ALPHANUMERIC','data_chunk',1,'p_data_chunk0','/home/sal/workspace/mt940/src/mt940/parser.py',90),
  ('data_chunk -> data_chunk data_chunk','data_chunk',2,'p_data_chunk1','/home/sal/workspace/mt940/src/mt940/parser.py',97),
  ('header_block -> { data_chunk COLON data_chunk }','header_block',5,'p_header_block','/home/sal/workspace/mt940/src/mt940/parser.py',104),
  ('header_block -> { data_chunk COLON fields }','header_block',5,'p_header_block','/home/sal/workspace/mt940/src/mt940/parser.py',105),
  ('header_block -> { data_chunk COLON swift_message }','header_block',5,'p_header_block','/home/sal/workspace/mt940/src/mt940/parser.py',106),
  ('fields -> TERMINAL_FIELD','fields',1,'p_fields0','/home/sal/workspace/mt940/src/mt940/parser.py',113),
  ('fields -> value_fields TERMINAL_FIELD','fields',2,'p_fields1','/home/sal/workspace/mt940/src/mt940/parser.py',120),
  ('value_fields -> value_field','value_fields',1,'p_value_fields0','/home/sal/workspace/mt940/src/mt940/parser.py',127),
  ('value_fields -> value_fields value_field','value_fields',2,'p_value_fields1','/home/sal/workspace/mt940/src/mt940/parser.py',134),
  ('value_field -> FIELD_SEPARATOR data_chunk COLON field_data','value_field',4,'p_value_field','/home/sal/workspace/mt940/src/mt940/parser.py',141),
  ('field_data -> data_chunk','field_data',1,'p_field_data0','/home/sal/workspace/mt940/src/mt940/parser.py',148),
  ('subfield_separator -> COLON','subfield_separator',1,'p_subfield_separator','/home/sal/workspace/mt940/src/mt940/parser.py',155),
  ('subfield_separator -> NEWLINE','subfield_separator',1,'p_subfield_separator','/home/sal/workspace/mt940/src/mt940/parser.py',156),
  ('subfield_separator -> /','subfield_separator',1,'p_subfield_separator','/home/sal/workspace/mt940/src/mt940/parser.py',157),
  ('subfield_separator -> ,','subfield_separator',1,'p_subfield_separator','/home/sal/workspace/mt940/src/mt940/parser.py',158),
  ('field_data -> field_data subfield_separator data_chunk','field_data',3,'p_field_data1','/home/sal/workspace/mt940/src/mt940/parser.py',165),
]
