__version__ = "0.3.3"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(HEAD detached at v0.3.3)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '01629f15d543637ebc51f77d4cc666e436f6e11d'
__git_head_subject__ = 'create issue: support for select fields'
__git_head_message__ = ''
__git_dirty_diff__ = ''