#!/usr/bin/env python

## NOTE: ##
## this setup.py was generated by zero2pypi:
## http://gfxmonk.net/dist/0install/zero2pypi.xml

from setuptools import *
setup(
	packages = find_packages(exclude=['test', 'test.*']),
	description='erlang-style concurrency library for python',
	install_requires=['setuptools'],
	long_description='\n**Note**: This package has been built automatically by\n`zero2pypi <http://gfxmonk.net/dist/0install/zero2pypi.xml>`_.\nIf possible, you should use the zero-install feed instead:\nhttp://gfxmonk.net/dist/0install/paragram.xml\n\n----------------\n\nParagram is an erlang-style concurrency framework for python. This is also known\nas an `actor-based concurrency model <http://en.wikipedia.org/wiki/Actor_model>`_,\nas it consists of multiple independent `actors` sending messages to each other.\n\nParagram started as a fork of `candygram`_\nadding true concurrency using threads and processes, but diverged enough to become its\nown library.\n\n**For documentation, installation**, etc, please see the\n`online documentation <http://gfxmonk.net/dist/doc/paragram/doc/>`_\n\n.. _candygram: http://candygram.sourceforge.net/\n',
	name='paragram',
	py_modules=['process_ring'],
	url='http://gfxmonk.net/dist/0install/paragram.xml',
	version='0.1.2',
)
