
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.2b2'
version_full = '6a02e05b7717e515462faf1e9e37727eb5ebe397'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
