language: python
python: 2.7
env:
- TOX_ENV=py26
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=pypy
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=manifest
install:
- pip install tox coveralls
script:
- tox --hashseed 0 -e $TOX_ENV
after_success:
- coveralls
notifications:
  email: false
  irc: "chat.freenode.net#ramlfications"
  slack:
    secure: RGdJmcQiapxCZWALwbogYykeuqUWhKgFtMR7JgRqPg/swcqbvD2rWYkT7eqUBrUldU7dTFhXt0RRqBf6J5vm4WcvkY5heQ4OpTi7R4itIiMLPndN24eG//PaOMhqrUyjkCsrWb0B7nuGRXmnH0C5xkPS/Dz1acugPG7zzXBKbKk=
deploy:
  provider: pypi
  user: roguelynn
  password:
    secure: XgUz7PiCHCOVM1yZeNfuy2j73aAGpW5HtTocmjlKNqG9wKXGkqV4IFWneznE1n8hqQj+Tqmm4MQ0AftJcomEh9WESVsglwMOqwMericRcsVkrEq+XHPynMfqsUc/MEr+zAB/Tj9SsbYMjP8zsk4TdJx/s+EbYFXsDfHrxcQY6q4=
  on:
    tags: true
  distributions: sdist bdist_wheel
