-- File: issue_98_1.vhd
-- Generated by MyHDL 0.9.0
-- Date: Sun Jul 12 13:49:50 2015


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_090.all;

entity issue_98_1 is
    port (
        sda: inout std_logic;
        scl: inout std_logic;
        sda_i: out std_logic;
        sda_o: in std_logic;
        scl_i: out std_logic;
        scl_o: in std_logic
    );
end entity issue_98_1;


architecture MyHDL of issue_98_1 is





signal scl_d: std_logic;

begin



scl <= scl_d;




sda_i <= sda;
scl_i <= scl;
scl_d <= 'Z';

end architecture MyHDL;
