# Generated by setup.py for PyCBC on 2015-06-22 17:39:44 +0000.

version = '1.0.1'
date = '2015-06-22 17:39:09 +0000'
release = True

git_hash = 'ecd56c48162f09984060b5313eaab92aa2dd8d45'
git_branch = 'master'
git_tag = 'v1.0.1'
git_author = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_committer = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Alexander Harvey Nitz <alex.nitz@gmail.com>'
git_build_date = '2015-06-22 17:39:44 +0000'
git_verbose_msg = """Branch: master
Tag: v1.0.1
Id: ecd56c48162f09984060b5313eaab92aa2dd8d45
Builder: Alexander Harvey Nitz <alex.nitz@gmail.com>
Build date: 2015-06-22 17:39:44 +0000
Repository status is CLEAN: All modifications committed"""