
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.11'
version_full = '4e5c22fba42ed7b3ce3cfedb2d22cbc610b7e9de'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

