---
site:
  title: Chert
  author: Chert Chertington
  tagline: Sharp and sparky static sites
  copyright: >-
    &copy; 2015 <img height="14" src="/img/by-sa.png" />
  main_links:
    - text: About
      href: /about.html
    - text: Github
      href: https://github.com/mahmoud/chert
      desc: Chert source code
    - text: Twitter
      href: https://twitter.com/mhashemi

dev:
  server_host: 0.0.0.0
  server_port: 8080
  base_url: /

prod:
  canonical_domain: http://sedimental.org
  canonical_base_path: /
  remote_host: sedimental.org
  remote_user: chert_user
  remote_path: /home/chert_user/my_site/public
  # rsync_cmd: rsync
  # rsync_flags: avzP
