
# This file was generated by PyScaffold from the git
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.5'
version_full = 'b88040d604ff187d515229071ec4da51d5e891c9'
def get_versions(default=dict(), verbose=False):
    return dict(version=version_version, full=version_full)
