__version__ = "0.4.1"
__git_commiter_name__ = "Shai Keren"
__git_commiter_email__ = "shaik@infinidat.com"
__git_branch__ = '(detached from v0.4.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '649a58c57659433d13de2ef559b28fc5b0d24ce6'
__git_head_subject__ = 'TRIVIAL opening files in non-blocking mode in solaris'
__git_head_message__ = ''
__git_dirty_diff__ = ''