
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.2.3'
version_full = '26cf4fc3217e95a923ac899b2ea340a7b48a77e2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

