# This file was auto-generated by salt's setup on Thursday, 04 June 2015 @ 16:06:25 UTC.

from salt.version import SaltStackVersion

__saltstack_version__ = SaltStackVersion(2015, 5, 2, 0, 0, 0, None)
