"""empty message

Revision ID: 3c73f5517a2
Revises: 425ac7b3d58
Create Date: 2015-06-07 02:29:33.522361

"""

# revision identifiers, used by Alembic.
revision = '3c73f5517a2'
down_revision = '425ac7b3d58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pictures_size'), 'pictures', ['size'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pictures_size'), table_name='pictures')
    op.drop_column('pictures', 'size')
    ### end Alembic commands ###
