
# This file was generated by 'versioneer.py' (0.13) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.10'
version_full = '2df74d3bb83b96a773c4d31b7047b60dc0ed17e7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

