
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.1'
version_full = '93e5da25120393ff36faef9a9b14086ac130382a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

