__version__ = "0.4.4"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(HEAD detached at v0.4.4)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '3b399b64036f3295d5c8b5b93bf653a80fbb07f8'
__git_head_subject__ = 'STORAGEMODEL-349 ReportLuns now raises exceptions when fails to normalize lun list'
__git_head_message__ = ''
__git_dirty_diff__ = ''