language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.2.x
- PLONE_VERSION=4.3.x
- PLONE_VERSION=5.x
install:
- python bootstrap.py -v 1.7.1 -c test-$PLONE_VERSION.cfg
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg annotate
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg
script:
- bin/code-analysis
- bin/test
after_success:
- bin/coverage run --source=plone.app.tiles bin/test --layer=\!PloneAppTilesLayer
- bin/coveralls
