---
- name: restart slurm
  action: service name={{slurm_name}} state=restarted

- name: restart slurmdbd
  action: service name={{slurmdbd_name}} state=restarted

- name: restart munge
  action: service name=munge state=restarted

- name: mount home
  action: shell mount /home

