sudo: required
language: python
virtualenv:
  system_site_packages: false
env:
  - DISTRIB="conda" COVERAGE="true" PYTHON_VERSION="2.7"
addons:
  apt_packages:
    - libbz2-dev
    - libhdf5-serial-dev
    - liblzo2-dev
# command to install dependencies
install: source continuous_integration/install.sh
# command to run tests
script: nosetests -sv --with-coverage --cover-package=pysemantic
after_success:
  coveralls
