language: python
python:
    - "2.7"
install:
    - pip install -r requirements/develop.txt
    - pip install -r requirements/travis.txt
script:
    - tox
    - tox -e docs
after_success:
    - coveralls
